export enum ChatEvents {
  Connected = 'connected',
  Disconnected = 'disconnected',
  NewMessage = 'newMessage',
  Join = 'join',
  IsTyping = 'isTyping',
  FindChats = 'findChats',
  FindMessages = 'findMessages',
  RemoveMessage = 'removeMessage',
  RemoveChat = 'removeChat',
  FindUser = 'findUser',
  BlockUser = 'blockUser',
  UnblockUser = 'unblockUser',
  SeenMessage = 'seenMessage',
  Notification = 'notification',
  ClearNotifications = 'clearNotifications',
  Error = 'error',
}
